version: "3.7"

services:
  nodeIS:
    container_name: "nodeIS"
    image: "node:12.22.0"
    working_dir: '/var/www/html'
    volumes:
      - ./../:/var/www/html
    ports:
      - "${PORT}:${PORT}"
    stdin_open: true

  mongoIS:
    container_name: "mongoIS"
    image: library/mongo:bionic
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
